webtalk_init -webtalk_dir D:/MASTER_2021/ADVANCED_VLSI/Verilog_Programs/SERVO_CONTROL/SERVO_VIVADO/SERVO_CONTROL/SERVO_CONTROL.sim/sim_1/behav/xsim/xsim.dir/Servo_2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 29 15:29:53 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "49dc0eef-2ccf-4696-80ba-d07c60d19933" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a32b5b4cc24b411a8cd29a7a8595d171" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20023861812 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "10000" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1417.51_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16484_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1298268007 -regid "" -xml D:/MASTER_2021/ADVANCED_VLSI/Verilog_Programs/SERVO_CONTROL/SERVO_VIVADO/SERVO_CONTROL/SERVO_CONTROL.sim/sim_1/behav/xsim/xsim.dir/Servo_2_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MASTER_2021/ADVANCED_VLSI/Verilog_Programs/SERVO_CONTROL/SERVO_VIVADO/SERVO_CONTROL/SERVO_CONTROL.sim/sim_1/behav/xsim/xsim.dir/Servo_2_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MASTER_2021/ADVANCED_VLSI/Verilog_Programs/SERVO_CONTROL/SERVO_VIVADO/SERVO_CONTROL/SERVO_CONTROL.sim/sim_1/behav/xsim/xsim.dir/Servo_2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
